from .affichage import *
from .backofword_binaire import *
from .backofword_occurence import *
from .distance_euclidienne import matrix_distance_Euclidienne
from .distance_manathan import matrix_distance_Manhattan
from .distance_cosinus import matrice_distance_cosinus
from .distance_hamming import *
from .distance_jacard import *
from .distance_bray_curtis import *
from .distance_kullback_leibler import *
from .matrix_normalise import *
from .pretraitement import *
from .tf_idf_norm import *
from .tf_idf_new import *
from .tf_idf_occ import *
from .tf_idf_bin import *