from .backofword_binaire import *
from .backofword_occurence import *
from .distance_euclidienne import *
from .distance_manathan import *
from .distance_cosinus import *
from .distance_hamming import *
from .distance_jacard import *
from .distance_bray_curtis import *
from .distance_kullback_leibler import *
from .matrix_normalise import *
from .pretraitement import *
from .tf_idf_norm import *
from .tf_idf_new import *
from .tf_idf_occ import *
from .tf_idf_bin import *
from .matrice_similarite import *
from .k_plus_proches_documents import *
from .utils import *